[project]
name = "cprenderer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "moderngl>=5.12.0",
    "moderngl-window>=3.1.1",
    "usd-core>=25.8",
]
